-- DDL:

-- sbgames2025.matches 

CREATE TABLE `matches` (
  `match_id` varchar(20) NOT NULL,
  `player_summoner_id` varchar(100) NOT NULL,
  `player_champion` varchar(50) DEFAULT NULL,
  `player_won` int DEFAULT NULL,
  `player_team` varchar(10) DEFAULT NULL,
  `player_lane` varchar(10) DEFAULT NULL,
  `player_role` varchar(20) DEFAULT NULL,
  `player_position` varchar(20) DEFAULT NULL,
  `game_duration` int DEFAULT NULL,
  `game_mode` varchar(50) DEFAULT NULL,
  `game_start_timestamp` bigint DEFAULT NULL,
  `team1_won` int DEFAULT NULL,
  `player_kills` int DEFAULT NULL,
  `player_deaths` int DEFAULT NULL,
  `player_assists` int DEFAULT NULL,
  `team1_champion1` varchar(50) DEFAULT NULL,
  `team1_champion2` varchar(50) DEFAULT NULL,
  `team1_champion3` varchar(50) DEFAULT NULL,
  `team1_champion4` varchar(50) DEFAULT NULL,
  `team1_champion5` varchar(50) DEFAULT NULL,
  `team2_champion1` varchar(50) DEFAULT NULL,
  `team2_champion2` varchar(50) DEFAULT NULL,
  `team2_champion3` varchar(50) DEFAULT NULL,
  `team2_champion4` varchar(50) DEFAULT NULL,
  `team2_champion5` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`match_id`,`player_summoner_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 1 - champion_performance.csv:

SELECT
    player_champion,
    COUNT(*) AS total_matches,
    SUM(player_won) AS total_wins,
    SUM(player_won) / COUNT(*) AS win_rate
FROM
    matches
GROUP BY
    player_champion
order BY 4

-- 2 - player_pools.csv:

SELECT
    m.player_summoner_id,
    COUNT(*) AS total_matches,
    SUM(m.player_won) AS total_wins,
    (COUNT(*) - SUM(m.player_won)) AS total_losses,
    (SUM(m.player_won) / COUNT(*)) AS win_rate,
    MAX(CASE WHEN m.player_champion = 'Lulu' THEN 1 ELSE 0 END) AS Lulu,
    MAX(CASE WHEN m.player_champion = 'Ashe' THEN 1 ELSE 0 END) AS Ashe,
    MAX(CASE WHEN m.player_champion = 'Karma' THEN 1 ELSE 0 END) AS Karma,
    MAX(CASE WHEN m.player_champion = 'Khazix' THEN 1 ELSE 0 END) AS Khazix,
    MAX(CASE WHEN m.player_champion = 'Leblanc' THEN 1 ELSE 0 END) AS Leblanc,
    MAX(CASE WHEN m.player_champion = 'Zed' THEN 1 ELSE 0 END) AS Zed,
    MAX(CASE WHEN m.player_champion = 'Pantheon' THEN 1 ELSE 0 END) AS Pantheon,
    MAX(CASE WHEN m.player_champion = 'MissFortune' THEN 1 ELSE 0 END) AS MissFortune,
    MAX(CASE WHEN m.player_champion = 'Aphelios' THEN 1 ELSE 0 END) AS Aphelios,
    MAX(CASE WHEN m.player_champion = 'MasterYi' THEN 1 ELSE 0 END) AS MasterYi,
    MAX(CASE WHEN m.player_champion = 'Seraphine' THEN 1 ELSE 0 END) AS Seraphine,
    MAX(CASE WHEN m.player_champion = 'Lux' THEN 1 ELSE 0 END) AS Lux,
    MAX(CASE WHEN m.player_champion = 'Jhin' THEN 1 ELSE 0 END) AS Jhin,
    MAX(CASE WHEN m.player_champion = 'Ekko' THEN 1 ELSE 0 END) AS Ekko,
    MAX(CASE WHEN m.player_champion = 'Vayne' THEN 1 ELSE 0 END) AS Vayne,
    MAX(CASE WHEN m.player_champion = 'LeeSin' THEN 1 ELSE 0 END) AS LeeSin,
    MAX(CASE WHEN m.player_champion = 'Lucian' THEN 1 ELSE 0 END) AS Lucian,
    MAX(CASE WHEN m.player_champion = 'Sylas' THEN 1 ELSE 0 END) AS Sylas,
    MAX(CASE WHEN m.player_champion = 'Riven' THEN 1 ELSE 0 END) AS Riven,
    MAX(CASE WHEN m.player_champion = 'Ezreal' THEN 1 ELSE 0 END) AS Ezreal,
    MAX(CASE WHEN m.player_champion = 'Kaisa' THEN 1 ELSE 0 END) AS Kaisa,
    MAX(CASE WHEN m.player_champion = 'Caitlyn' THEN 1 ELSE 0 END) AS Caitlyn,
    MAX(CASE WHEN m.player_champion = 'Fiora' THEN 1 ELSE 0 END) AS Fiora,
    MAX(CASE WHEN m.player_champion = 'XinZhao' THEN 1 ELSE 0 END) AS XinZhao,
    MAX(CASE WHEN m.player_champion = 'Sona' THEN 1 ELSE 0 END) AS Sona,
    MAX(CASE WHEN m.player_champion = 'Syndra' THEN 1 ELSE 0 END) AS Syndra,
    MAX(CASE WHEN m.player_champion = 'Graves' THEN 1 ELSE 0 END) AS Graves,
    MAX(CASE WHEN m.player_champion = 'Qiyana' THEN 1 ELSE 0 END) AS Qiyana,
    MAX(CASE WHEN m.player_champion = 'Belveth' THEN 1 ELSE 0 END) AS Belveth,
    MAX(CASE WHEN m.player_champion = 'KSante' THEN 1 ELSE 0 END) AS KSante,
    MAX(CASE WHEN m.player_champion = 'Draven' THEN 1 ELSE 0 END) AS Draven,
    MAX(CASE WHEN m.player_champion = 'Sejuani' THEN 1 ELSE 0 END) AS Sejuani,
    MAX(CASE WHEN m.player_champion = 'Rengar' THEN 1 ELSE 0 END) AS Rengar,
    MAX(CASE WHEN m.player_champion = 'Azir' THEN 1 ELSE 0 END) AS Azir,
    MAX(CASE WHEN m.player_champion = 'Swain' THEN 1 ELSE 0 END) AS Swain,
    MAX(CASE WHEN m.player_champion = 'Zyra' THEN 1 ELSE 0 END) AS Zyra,
    MAX(CASE WHEN m.player_champion = 'Twitch' THEN 1 ELSE 0 END) AS Twitch,
    MAX(CASE WHEN m.player_champion = 'Kayn' THEN 1 ELSE 0 END) AS Kayn,
    MAX(CASE WHEN m.player_champion = 'Trundle' THEN 1 ELSE 0 END) AS Trundle,
    MAX(CASE WHEN m.player_champion = 'Hecarim' THEN 1 ELSE 0 END) AS Hecarim,
    MAX(CASE WHEN m.player_champion = 'Samira' THEN 1 ELSE 0 END) AS Samira,
    MAX(CASE WHEN m.player_champion = 'Jayce' THEN 1 ELSE 0 END) AS Jayce,
    MAX(CASE WHEN m.player_champion = 'Xayah' THEN 1 ELSE 0 END) AS Xayah,
    MAX(CASE WHEN m.player_champion = 'Shaco' THEN 1 ELSE 0 END) AS Shaco,
    MAX(CASE WHEN m.player_champion = 'Rell' THEN 1 ELSE 0 END) AS Rell,
    MAX(CASE WHEN m.player_champion = 'Chogath' THEN 1 ELSE 0 END) AS Chogath,
    MAX(CASE WHEN m.player_champion = 'Rumble' THEN 1 ELSE 0 END) AS Rumble,
    MAX(CASE WHEN m.player_champion = 'Jax' THEN 1 ELSE 0 END) AS Jax,
    MAX(CASE WHEN m.player_champion = 'Kennen' THEN 1 ELSE 0 END) AS Kennen,
    MAX(CASE WHEN m.player_champion = 'Vi' THEN 1 ELSE 0 END) AS Vi,
    MAX(CASE WHEN m.player_champion = 'Nocturne' THEN 1 ELSE 0 END) AS Nocturne,
    MAX(CASE WHEN m.player_champion = 'Yone' THEN 1 ELSE 0 END) AS Yone,
    MAX(CASE WHEN m.player_champion = 'Tristana' THEN 1 ELSE 0 END) AS Tristana,
    MAX(CASE WHEN m.player_champion = 'Katarina' THEN 1 ELSE 0 END) AS Katarina,
    MAX(CASE WHEN m.player_champion = 'TwistedFate' THEN 1 ELSE 0 END) AS TwistedFate,
    MAX(CASE WHEN m.player_champion = 'Lissandra' THEN 1 ELSE 0 END) AS Lissandra,
    MAX(CASE WHEN m.player_champion = 'Malphite' THEN 1 ELSE 0 END) AS Malphite,
    MAX(CASE WHEN m.player_champion = 'Singed' THEN 1 ELSE 0 END) AS Singed,
    MAX(CASE WHEN m.player_champion = 'Gangplank' THEN 1 ELSE 0 END) AS Gangplank,
    MAX(CASE WHEN m.player_champion = 'Gragas' THEN 1 ELSE 0 END) AS Gragas,
    MAX(CASE WHEN m.player_champion = 'Yorick' THEN 1 ELSE 0 END) AS Yorick,
    MAX(CASE WHEN m.player_champion = 'Senna' THEN 1 ELSE 0 END) AS Senna,
    MAX(CASE WHEN m.player_champion = 'Galio' THEN 1 ELSE 0 END) AS Galio,
    MAX(CASE WHEN m.player_champion = 'RekSai' THEN 1 ELSE 0 END) AS RekSai,
    MAX(CASE WHEN m.player_champion = 'Elise' THEN 1 ELSE 0 END) AS Elise,
    MAX(CASE WHEN m.player_champion = 'JarvanIV' THEN 1 ELSE 0 END) AS JarvanIV,
    MAX(CASE WHEN m.player_champion = 'Diana' THEN 1 ELSE 0 END) AS Diana,
    MAX(CASE WHEN m.player_champion = 'Morgana' THEN 1 ELSE 0 END) AS Morgana,
    MAX(CASE WHEN m.player_champion = 'Aatrox' THEN 1 ELSE 0 END) AS Aatrox,
    MAX(CASE WHEN m.player_champion = 'Soraka' THEN 1 ELSE 0 END) AS Soraka,
    MAX(CASE WHEN m.player_champion = 'Lillia' THEN 1 ELSE 0 END) AS Lillia,
    MAX(CASE WHEN m.player_champion = 'Viego' THEN 1 ELSE 0 END) AS Viego,
    MAX(CASE WHEN m.player_champion = 'Nautilus' THEN 1 ELSE 0 END) AS Nautilus,
    MAX(CASE WHEN m.player_champion = 'Poppy' THEN 1 ELSE 0 END) AS Poppy,
    MAX(CASE WHEN m.player_champion = 'Teemo' THEN 1 ELSE 0 END) AS Teemo,
    MAX(CASE WHEN m.player_champion = 'Ornn' THEN 1 ELSE 0 END) AS Ornn,
    MAX(CASE WHEN m.player_champion = 'Thresh' THEN 1 ELSE 0 END) AS Thresh,
    MAX(CASE WHEN m.player_champion = 'Taric' THEN 1 ELSE 0 END) AS Taric,
    MAX(CASE WHEN m.player_champion = 'Volibear' THEN 1 ELSE 0 END) AS Volibear,
    MAX(CASE WHEN m.player_champion = 'Fizz' THEN 1 ELSE 0 END) AS Fizz,
    MAX(CASE WHEN m.player_champion = 'Darius' THEN 1 ELSE 0 END) AS Darius,
    MAX(CASE WHEN m.player_champion = 'Mordekaiser' THEN 1 ELSE 0 END) AS Mordekaiser,
    MAX(CASE WHEN m.player_champion = 'Akali' THEN 1 ELSE 0 END) AS Akali,
    MAX(CASE WHEN m.player_champion = 'Varus' THEN 1 ELSE 0 END) AS Varus,
    MAX(CASE WHEN m.player_champion = 'Kalista' THEN 1 ELSE 0 END) AS Kalista,
    MAX(CASE WHEN m.player_champion = 'Brand' THEN 1 ELSE 0 END) AS Brand,
    MAX(CASE WHEN m.player_champion = 'Urgot' THEN 1 ELSE 0 END) AS Urgot,
    MAX(CASE WHEN m.player_champion = 'Renekton' THEN 1 ELSE 0 END) AS Renekton,
    MAX(CASE WHEN m.player_champion = 'Briar' THEN 1 ELSE 0 END) AS Briar,
    MAX(CASE WHEN m.player_champion = 'Pyke' THEN 1 ELSE 0 END) AS Pyke,
    MAX(CASE WHEN m.player_champion = 'Ahri' THEN 1 ELSE 0 END) AS Ahri,
    MAX(CASE WHEN m.player_champion = 'KogMaw' THEN 1 ELSE 0 END) AS KogMaw,
    MAX(CASE WHEN m.player_champion = 'Kindred' THEN 1 ELSE 0 END) AS Kindred,
    MAX(CASE WHEN m.player_champion = 'Xerath' THEN 1 ELSE 0 END) AS Xerath,
    MAX(CASE WHEN m.player_champion = 'Udyr' THEN 1 ELSE 0 END) AS Udyr,
    MAX(CASE WHEN m.player_champion = 'Veigar' THEN 1 ELSE 0 END) AS Veigar,
    MAX(CASE WHEN m.player_champion = 'Leona' THEN 1 ELSE 0 END) AS Leona,
    MAX(CASE WHEN m.player_champion = 'Nami' THEN 1 ELSE 0 END) AS Nami,
    MAX(CASE WHEN m.player_champion = 'Evelynn' THEN 1 ELSE 0 END) AS Evelynn,
    MAX(CASE WHEN m.player_champion = 'Yuumi' THEN 1 ELSE 0 END) AS Yuumi,
    MAX(CASE WHEN m.player_champion = 'Alistar' THEN 1 ELSE 0 END) AS Alistar,
    MAX(CASE WHEN m.player_champion = 'Nilah' THEN 1 ELSE 0 END) AS Nilah,
    MAX(CASE WHEN m.player_champion = 'Illaoi' THEN 1 ELSE 0 END) AS Illaoi,
    MAX(CASE WHEN m.player_champion = 'Heimerdinger' THEN 1 ELSE 0 END) AS Heimerdinger,
    MAX(CASE WHEN m.player_champion = 'Kassadin' THEN 1 ELSE 0 END) AS Kassadin,
    MAX(CASE WHEN m.player_champion = 'Hwei' THEN 1 ELSE 0 END) AS Hwei,
    MAX(CASE WHEN m.player_champion = 'Milio' THEN 1 ELSE 0 END) AS Milio,
    MAX(CASE WHEN m.player_champion = 'Blitzcrank' THEN 1 ELSE 0 END) AS Blitzcrank,
    MAX(CASE WHEN m.player_champion = 'Anivia' THEN 1 ELSE 0 END) AS Anivia,
    MAX(CASE WHEN m.player_champion = 'Olaf' THEN 1 ELSE 0 END) AS Olaf,
    MAX(CASE WHEN m.player_champion = 'Corki' THEN 1 ELSE 0 END) AS Corki,
    MAX(CASE WHEN m.player_champion = 'Akshan' THEN 1 ELSE 0 END) AS Akshan,
    MAX(CASE WHEN m.player_champion = 'FiddleSticks' THEN 1 ELSE 0 END) AS FiddleSticks,
    MAX(CASE WHEN m.player_champion = 'Rakan' THEN 1 ELSE 0 END) AS Rakan,
    MAX(CASE WHEN m.player_champion = 'Orianna' THEN 1 ELSE 0 END) AS Orianna,
    MAX(CASE WHEN m.player_champion = 'Sivir' THEN 1 ELSE 0 END) AS Sivir,
    MAX(CASE WHEN m.player_champion = 'Maokai' THEN 1 ELSE 0 END) AS Maokai,
    MAX(CASE WHEN m.player_champion = 'Ivern' THEN 1 ELSE 0 END) AS Ivern,
    MAX(CASE WHEN m.player_champion = 'Janna' THEN 1 ELSE 0 END) AS Janna,
    MAX(CASE WHEN m.player_champion = 'Naafiri' THEN 1 ELSE 0 END) AS Naafiri,
    MAX(CASE WHEN m.player_champion = 'Yasuo' THEN 1 ELSE 0 END) AS Yasuo,
    MAX(CASE WHEN m.player_champion = 'Nasus' THEN 1 ELSE 0 END) AS Nasus,
    MAX(CASE WHEN m.player_champion = 'DrMundo' THEN 1 ELSE 0 END) AS DrMundo,
    MAX(CASE WHEN m.player_champion = 'Smolder' THEN 1 ELSE 0 END) AS Smolder,
    MAX(CASE WHEN m.player_champion = 'Irelia' THEN 1 ELSE 0 END) AS Irelia,
    MAX(CASE WHEN m.player_champion = 'Neeko' THEN 1 ELSE 0 END) AS Neeko,
    MAX(CASE WHEN m.player_champion = 'Renata' THEN 1 ELSE 0 END) AS Renata,
    MAX(CASE WHEN m.player_champion = 'Sett' THEN 1 ELSE 0 END) AS Sett,
    MAX(CASE WHEN m.player_champion = 'Jinx' THEN 1 ELSE 0 END) AS Jinx,
    MAX(CASE WHEN m.player_champion = 'Viktor' THEN 1 ELSE 0 END) AS Viktor,
    MAX(CASE WHEN m.player_champion = 'Zeri' THEN 1 ELSE 0 END) AS Zeri,
    MAX(CASE WHEN m.player_champion = 'Ziggs' THEN 1 ELSE 0 END) AS Ziggs,
    MAX(CASE WHEN m.player_champion = 'Shyvana' THEN 1 ELSE 0 END) AS Shyvana,
    MAX(CASE WHEN m.player_champion = 'Annie' THEN 1 ELSE 0 END) AS Annie,
    MAX(CASE WHEN m.player_champion = 'Malzahar' THEN 1 ELSE 0 END) AS Malzahar,
    MAX(CASE WHEN m.player_champion = 'Vladimir' THEN 1 ELSE 0 END) AS Vladimir,
    MAX(CASE WHEN m.player_champion = 'Camille' THEN 1 ELSE 0 END) AS Camille,
    MAX(CASE WHEN m.player_champion = 'Zilean' THEN 1 ELSE 0 END) AS Zilean,
    MAX(CASE WHEN m.player_champion = 'Karthus' THEN 1 ELSE 0 END) AS Karthus,
    MAX(CASE WHEN m.player_champion = 'Taliyah' THEN 1 ELSE 0 END) AS Taliyah,
    MAX(CASE WHEN m.player_champion = 'Ryze' THEN 1 ELSE 0 END) AS Ryze,
    MAX(CASE WHEN m.player_champion = 'Shen' THEN 1 ELSE 0 END) AS Shen,
    MAX(CASE WHEN m.player_champion = 'Braum' THEN 1 ELSE 0 END) AS Braum,
    MAX(CASE WHEN m.player_champion = 'Zac' THEN 1 ELSE 0 END) AS Zac,
    MAX(CASE WHEN m.player_champion = 'MonkeyKing' THEN 1 ELSE 0 END) AS MonkeyKing,
    MAX(CASE WHEN m.player_champion = 'Nidalee' THEN 1 ELSE 0 END) AS Nidalee,
    MAX(CASE WHEN m.player_champion = 'Rammus' THEN 1 ELSE 0 END) AS Rammus,
    MAX(CASE WHEN m.player_champion = 'Sion' THEN 1 ELSE 0 END) AS Sion,
    MAX(CASE WHEN m.player_champion = 'Kled' THEN 1 ELSE 0 END) AS Kled,
    MAX(CASE WHEN m.player_champion = 'Vex' THEN 1 ELSE 0 END) AS Vex,
    MAX(CASE WHEN m.player_champion = 'Gwen' THEN 1 ELSE 0 END) AS Gwen,
    MAX(CASE WHEN m.player_champion = 'AurelionSol' THEN 1 ELSE 0 END) AS AurelionSol,
    MAX(CASE WHEN m.player_champion = 'Quinn' THEN 1 ELSE 0 END) AS Quinn,
    MAX(CASE WHEN m.player_champion = 'Gnar' THEN 1 ELSE 0 END) AS Gnar,
    MAX(CASE WHEN m.player_champion = 'Amumu' THEN 1 ELSE 0 END) AS Amumu,
    MAX(CASE WHEN m.player_champion = 'Garen' THEN 1 ELSE 0 END) AS Garen,
    MAX(CASE WHEN m.player_champion = 'Kayle' THEN 1 ELSE 0 END) AS Kayle,
    MAX(CASE WHEN m.player_champion = 'Bard' THEN 1 ELSE 0 END) AS Bard,
    MAX(CASE WHEN m.player_champion = 'Nunu' THEN 1 ELSE 0 END) AS Nunu,
    MAX(CASE WHEN m.player_champion = 'Talon' THEN 1 ELSE 0 END) AS Talon,
    MAX(CASE WHEN m.player_champion = 'Cassiopeia' THEN 1 ELSE 0 END) AS Cassiopeia,
    MAX(CASE WHEN m.player_champion = 'Skarner' THEN 1 ELSE 0 END) AS Skarner,
    MAX(CASE WHEN m.player_champion = 'Tryndamere' THEN 1 ELSE 0 END) AS Tryndamere,
    MAX(CASE WHEN m.player_champion = 'Velkoz' THEN 1 ELSE 0 END) AS Velkoz,
    MAX(CASE WHEN m.player_champion = 'TahmKench' THEN 1 ELSE 0 END) AS TahmKench,
    MAX(CASE WHEN m.player_champion = 'Zoe' THEN 1 ELSE 0 END) AS Zoe,
    MAX(CASE WHEN m.player_champion = 'Warwick' THEN 1 ELSE 0 END) AS Warwick,
    MAX(CASE WHEN m.player_champion = 'Aurora' THEN 1 ELSE 0 END) AS Aurora,
    MAX(CASE WHEN m.player_champion = 'Ambessa' THEN 1 ELSE 0 END) AS Ambessa
FROM
    `matches` m
GROUP BY
    m.player_summoner_id;

--- 3- adjusted Select * 

SELECT
    match_id,
    player_summoner_id,
    player_champion,
    player_won as binary_win,
    CASE 
        WHEN player_won = 1 THEN 'Yes'
        WHEN player_won = 0 THEN 'No'
        ELSE 'Unknown'
    END AS win,  
    player_team,
    player_lane,
    player_role,
    player_position,
    game_duration,
    game_mode,
    FROM_UNIXTIME(
        CAST(
            REPLACE(game_start_timestamp, ',', '') AS UNSIGNED
        ) / 1000  
    ) AS game_start_datetime,  
    team1_won,
    player_kills,
    player_deaths,
    player_assists,
    team1_champion1,
    team1_champion2,
    team1_champion3,
    team1_champion4,
    team1_champion5,
    team2_champion1,
    team2_champion2,
    team2_champion3,
    team2_champion4,
    team2_champion5
FROM matches